import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const user = useUser();
  useEffect(() => {
    console.log({ user })
  }, [])

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-500">
        {/* <div className="bg-slate-50 w-16"> */}
        <div>
          {!user.isSignedIn && <SignIn />}
        </div>

        <div>
          {!!user.isSignedIn && <SignOutButton />}
        </div>
        {/* </div> */}

      </main>
    </>
  );
};

export default Home;
